{% set version = "1.12.0" %}

package:
  name: fastavro
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/f/fastavro/fastavro-{{ version }}.tar.gz
  sha256: a67a87be149825d74006b57e52be068dfa24f3bfc6382543ec92cd72327fe152

build:
  number: 0
  script:
    - export FASTAVRO_USE_CYTHON=1  # [not win]
    - set FASTAVRO_USE_CYTHON=1  # [win]
    - {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - fastavro = fastavro.__main__:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - cython
    - pip
    - setuptools
  run:
    - python

test:
  requires:
    - nose
    - flake8
  imports:
    - fastavro

about:
  home: https://github.com/fastavro/fastavro
  license: MIT
  license_file: LICENSE
  summary: Fast read/write of AVRO files
  dev_url: https://github.com/fastavro/fastavro

extra:
  recipe-maintainers:
    - mariusvniekerk
    - scottbelden
    - tebeka
    - fhoehle
