schema_version: 1

context:
  name: fastavro
  version: "1.13.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 6f05aa2539bf7a19e9eb3bdaf6580c4d0f082a8230f641eaf9c84e4bcf0e6bc4

build:
  number: 0
  script:
    env:
      FASTAVRO_USE_CYTHON: "1"
    content: ${{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  python:
    entry_points:
      - fastavro = fastavro.__main__:main

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - cython
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
  host:
    - python
    - cython
    - pip
    - setuptools
  run:
    - python

tests:
  - python:
      imports:
        - fastavro
      pip_check: true

about:
  license: MIT
  license_file: LICENSE
  summary: Fast read/write of AVRO files
  homepage: https://github.com/fastavro/fastavro
  repository: https://github.com/fastavro/fastavro

extra:
  recipe-maintainers:
    - mariusvniekerk
    - scottbelden
    - tebeka
    - fhoehle
